services:
  db:
    image: postgres:18-alpine3.22
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql

  app:
    image: luismeirelles/tutor-ai
    build: .docker/app
    working_dir: /var/www
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/var/www
      - ./.docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=${APP_PORT}
    environment:
      PHP_IDE_CONFIG: serverName=tutor-ai
    extra_hosts:
      - "host.docker.internal:host-gateway"

  laravel-boost:
    image: luismeirelles/tutor-ai
    profiles:
      - ai
    build: .docker/app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan boost:mcp
    stdin_open: true

  migrate:
    image: luismeirelles/tutor-ai
    build: .docker/app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    entrypoint: .docker/migrate/entrypoint.sh

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  queues:
    image: luismeirelles/tutor-ai
    build: .docker/app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    command: php artisan queue:listen --sleep=3 --tries=3
    tty: true

volumes:
  db_data:
